<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[addCustomer----> Test Script Execution Started]]>
    </line>
    <line>
      <![CDATA[addCustomerTest Script Execution not been completed]]>
    </line>
  </reporter-output>
  <suite started-at="2023-01-12T17:25:09 IST" name="Suite" finished-at="2023-01-12T17:25:27 IST" duration-ms="18508">
    <groups>
    </groups>
    <test started-at="2023-01-12T17:25:09 IST" name="Test" finished-at="2023-01-12T17:25:27 IST" duration-ms="18508">
      <class name="Customer_Module.CreateCustomer_POM_Test">
        <test-method is-config="true" signature="configBS_SIS()[pri:0, instance:Customer_Module.CreateCustomer_POM_Test@25fb8912]" started-at="2023-01-12T17:25:09 IST" name="configBS_SIS" finished-at="2023-01-12T17:25:09 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBS_SIS -->
        <test-method is-config="true" signature="configBC_SIS()[pri:0, instance:Customer_Module.CreateCustomer_POM_Test@25fb8912]" started-at="2023-01-12T17:25:09 IST" name="configBC_SIS" finished-at="2023-01-12T17:25:17 IST" duration-ms="8202" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBC_SIS -->
        <test-method is-config="true" signature="configBM_SIS()[pri:0, instance:Customer_Module.CreateCustomer_POM_Test@25fb8912]" started-at="2023-01-12T17:25:17 IST" name="configBM_SIS" finished-at="2023-01-12T17:25:18 IST" duration-ms="937" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM_SIS -->
        <test-method signature="addCustomer()[pri:0, instance:Customer_Module.CreateCustomer_POM_Test@25fb8912]" started-at="2023-01-12T17:25:18 IST" name="addCustomer" finished-at="2023-01-12T17:25:21 IST" duration-ms="2571" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at Customer_Module.CreateCustomer_POM_Test.addCustomer(CreateCustomer_POM_Test.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addCustomer----> Test Script Execution Started]]>
            </line>
            <line>
              <![CDATA[addCustomerTest Script Execution not been completed]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method is-config="true" signature="configAM_SIS()[pri:0, instance:Customer_Module.CreateCustomer_POM_Test@25fb8912]" started-at="2023-01-12T17:25:21 IST" name="configAM_SIS" finished-at="2023-01-12T17:25:26 IST" duration-ms="4363" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM_SIS -->
        <test-method is-config="true" signature="configAC_SIS()[pri:0, instance:Customer_Module.CreateCustomer_POM_Test@25fb8912]" started-at="2023-01-12T17:25:26 IST" name="configAC_SIS" finished-at="2023-01-12T17:25:27 IST" duration-ms="1329" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAC_SIS -->
        <test-method is-config="true" signature="configAS_SIS()[pri:0, instance:Customer_Module.CreateCustomer_POM_Test@25fb8912]" started-at="2023-01-12T17:25:28 IST" name="configAS_SIS" finished-at="2023-01-12T17:25:28 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAS_SIS -->
      </class> <!-- Customer_Module.CreateCustomer_POM_Test -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
